### ISSUE TITLE
runtime error when using metrics-jvm

### ISSUE THREAD

**Issue by bitkid** [dropwizard/metrics#769]
Caused by: java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
	at com.codahale.metrics.jvm.BufferPoolMetricSet.getMetrics(BufferPoolMetricSet.java:45)
	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:381)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
	at com.collective.dorado.util.VMInstrumentor.instrumentVM(VMInstrumentor.java:22)

testet with 3.1.0 and 3.1.1 (java 1.8.0_11-b12) works fine with 3.0.2

**Comment by bitkid** [comment]
ok .. my bad. had both on class path

**Comment by amitranjan-fk** [comment]
@bitkid what was the issue ?

**Comment by sisingh** [comment]
What was the reason buddy ?

**Comment by sisingh** [comment]
@bitkid : what was the reason. I am also facing the same issue.

**Comment by ryantenney** [comment]
If I understand @bitkid's last comment, he had multiple versions of metrics on the classpath.

**Comment by sisingh** [comment]
Sure just wanted to know where to put exclusion in maven.

**Comment by bradfordcp** [comment]
What is the resolution to this?

**Comment by ryantenney** [comment]
Multiple versions of metrics on the classpath.

**Comment by bradfordcp** [comment]
I was looking for a way to fix the issue. For anyone else having this problem the following command will help you track down where the extra inclusion is:

`mvn dependency:tree -Ddetail=true`

From there you can look at excluding the appropriate version from the dependency including the old version

```xml
<exclusions>
    <exclusion>
      <groupId>com.codahale.metrics</groupId>
      <artifactId>metrics-core</artifactId>
    </exclusion>
</exclusions>
```

Thanks for your help @ryantenney .

**Comment by mithunkhatri** [comment]
I faced the same issue. I excluded below jar and it worked.

```
<exclusion>
<artifactId>metrics-core</artifactId>
<groupId>io.dropwizard.metrics</groupId>
</exclusion>
```

**Comment by ferdi1809** [comment]
Thanks mithunkhatri . Excluding the **io.dropwizard.metrics** core metrics solved my issue.

**Comment by fommil** [comment]
What to do when you actually need to use `metrics-core`?

**Comment by arteam** [comment]
I think this issue is mostly about incompatibilities in the API between `metrics-core` 3.0.* and 3.1.* You need to track down an old version and exclude it.

**Comment by fommil** [comment]
nope, I only have 3.2.5 on my classpath. I checked several times. I'm seeing this exception on startup in YourKit's exception tracker.

**Comment by arteam** [comment]
Hm.., that's strange. The commit that introduced this issue is https://github.com/dropwizard/metrics/commit/0609cc695f486af5482b132ab89aeab392e88f82 and it was merged to 3.1.0. Could you post the whole stack trace?

**Comment by fommil** [comment]
sure... I'll grab it from Yourkit next time I'm doing a perf test.

**Comment by fommil** [comment]
this is in yourkit csv format...

```
"Reverse Call Tree","Count","Level"
"java.net.URLClassLoader.findClass(String) URLClassLoader.java:381","8892","1"
"sun.reflect.misc.MethodUtil.findClass(String) MethodUtil.java:343","12","1"
"com.yourkit.runtime.TelemetryThread.run() TelemetryThread.java:529","11","2"
"com.codahale.metrics.JmxAttributeGauge.getValue() JmxAttributeGauge.java:44","1","2"
"io.prometheus.client.dropwizard.DropwizardExports.fromGauge(String, Gauge) DropwizardExports.java:47","","3"
"io.prometheus.client.dropwizard.DropwizardExports.collect() DropwizardExports.java:133","","4"
"io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement() CollectorRegistry.java:180","","5"
"io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement() CollectorRegistry.java:213","","6"
"io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement() CollectorRegistry.java:134","","7"
"java.util.Collections.list(Enumeration) Collections.java:5240","","8"
"elided.push(CollectorRegistry) NamespacedGraphite.scala:29","","9"
"io.prometheus.client.bridge.Graphite$PushThread.run() Graphite.java:101","","10"
```

**Comment by arteam** [comment]
It seems to me that the error happens during reading a JMX attribute in the `JmxAttributeGauge#getValue` method, not in in the `JmxAttributeGauge` constructor. By the way, are you running under Java8 or Java9? I can imagine a JVM with disabled JMX. Can you reproduce the error without YourKit?

**Comment by fommil** [comment]
ah, now that's certainly possible. Sorry for the noise!
